name: CML
on:
  push:
    branches:
      - dev
  pull_request:
      branches:
        - main
permissions:
  contents: write
  pull-requests: write

jobs:
  test-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup CML (Continuous Machine Learning)
        uses: iterative/setup-cml@v2.0.1

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc[gcs]
      
      - name: Google Cloud Authentication
        id: 'auth'
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Pull Data and Model using dvc
        run: |
          dvc pull

      - name: Run Tests
        run: |
          pytest -v &> test_output.txt 
      
      - name: Model Evaluation
        run: |
          mkdir metrics
          python3 create_metrics.py
      
      - name: Read CSV
        id: csv
        uses: juliangruber/read-file-action@v1
        with:
          path: ./metrics/report.csv

      - name: Create MD
        uses: petems/csv-to-md-table-action@master
        id: table
        with:
          csvinput: ${{ steps.csv.outputs.content }}

      - name: Create cml report
        run: |
          echo "# CML Test & Evaluation Report" > report.md

          ## Section 1: Pytest Results
          echo "" >> report.md # Add a blank line for spacing
          echo "### Pytest Sanity Check" >> report.md
          echo "\`\`\`" >> report.md # Start a code block for the text output
          cat test_output.txt >> report.md
          echo "\`\`\`" >> report.md # End the code block

          ## Section 2: Evaluation Metrics Table
          echo "" >> report.md
          echo "### Evaluation Metrics" >> report.md
          echo "${{ steps.table.outputs.markdown-table }}" >> report.md

          ## Section 3: Confusion Matrix Visualization
          echo "" >> report.md
          echo "### Confusion Matrix" >> report.md
          echo "![](./metrics/confusion_matrix.png)" >> report.md

          cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
